import Link from "next/link";
import PageShell from "@/components/PageShell";
import { APP_URL } from "@/lib/site";
const sections = [
 ["A simple way to raise a problem", "A team member sends a message, photo or voice note. They can explain the issue in their own words, without stepping away from the working day to fill out a long form."],
 ["A clearer request for managers", "The report becomes a clear written request in English. The original message and supporting details stay available, helping managers understand the problem without searching through separate conversations."],
 ["Less chasing for missing details", "If something needs explaining, your team asks in the same conversation. The answer stays with the request, so the next person does not need to start from the beginning."],
 ["A shared view of what needs attention", "Managers can see requests waiting to be checked, review the details and record their decision. Staff access is managed by your organization, keeping responsibility with the right people."],
 ["A consistent approach across locations", "Give every location a familiar way to report issues and central teams a consistent starting point. Saveaday brings the information together; your team stays responsible for reviewing requests and arranging the next step."],
];
export default function ExperiencePage() { return <PageShell title="A simpler working day" description="See how Saveaday makes reporting easier for teams and gives managers a clearer view of everyday issues." path="/docs/"><section className="bg-[#071c1a] px-5 pb-16 pt-36 text-white sm:px-8 lg:px-12"><div className="mx-auto max-w-[1304px]"><p className="eyebrow !text-[#74EFC3]">The Saveaday experience</p><h1 className="mt-5 font-serif text-5xl leading-tight sm:text-6xl">Easy for the team.<br />Useful for the business.</h1><p className="mt-6 max-w-2xl leading-8 text-white/70">A practical way to reduce follow-up, keep the facts together and make everyday requests easier to manage.</p></div></section><section className="bg-[#f7faf9] px-5 py-16 sm:px-8 lg:px-12"><div className="mx-auto max-w-3xl">{sections.map(([title, body], i) => <article key={title} className="border-b border-[#dce6e2] py-8"><p className="eyebrow">0{i + 1}</p><h2 className="mt-3 font-serif text-3xl text-[#18332f]">{title}</h2><p className="mt-4 text-base leading-8 text-[#4d6460]">{body}</p></article>)}<div className="mt-10 flex flex-wrap gap-6"><Link href="/contact/" className="bg-[#071c1a] px-6 py-4 text-sm font-semibold text-white">Request a demo</Link><a href={APP_URL} className="px-6 py-4 text-sm font-semibold text-[#18332f] underline underline-offset-4">Already a customer? Sign in</a></div></div></section></PageShell>; }
